version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - PORT=4000
      - PASSWORD=${PASSWORD:-changeme}
      - DB_PATH=/data/notes.db
    volumes:
      - notes_data:/data
    ports:
      - '4000:4000'
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:4000/api
    ports:
      - '8080:80'
    depends_on:
      - backend
volumes:
  notes_data:
